export const logo = document.querySelector('.logo')
export const home_btn = document.querySelector('.home-btn')

export const a_home = document.querySelector('.a-home')
export const a_agents = document.querySelector('.a-agents')
export const a_weapons = document.querySelector('.a-weapons')
export const a_gears = document.querySelector('.a-gears')
export const a_maps = document.querySelector('.a-maps')

export const m_home = document.querySelector('.m-home')
export const m_agents = document.querySelector('.m-agents')
export const m_weapons = document.querySelector('.m-weapons')
export const m_gears = document.querySelector('.m-gears')
export const m_maps = document.querySelector('.m-maps')

export const open_menu = document.querySelector('.open-menu')
export const close_menu = document.querySelector('.close-menu')

export const header = document.querySelector('.header')
export const home = document.querySelector('.home')
export const agents = document.querySelector('.agents')
export const weapons = document.querySelector('.weapons')
export const gears = document.querySelector('.gears')
export const maps = document.querySelector('.maps')
export const footer = document.querySelector('.footer')

export const character = document.querySelector('.character')
export const content_modal = document.querySelector('.content-modal')
export const back = document.querySelector('.back')
export const guns = document.querySelector('.guns')
export const gear = document.querySelector('.gear')
export const map = document.querySelector('.map')

export const role_name = document.querySelector('.role-name')
export const role_icon = document.querySelector('.role-icon')
export const char_name = document.querySelector('.char-name')
export const char_desc = document.querySelector('.char-desc')
export const list_skills_img = document.querySelector('.list-skills-img')
export const skill_description = document.querySelector('.skill-description')

export const fullPortrait = document.querySelector('.fullPortrait')
export const sound = document.querySelector('.sound')
export const voice = new Audio()